### ISSUE TITLE
error on running.please remake.

### ISSUE THREAD

**Issue by sari777** [WanderingPhilosopher/Windows-KeySubtractor#3]
not compiled correctly.
giving the error on startup... bx000007....
what is it.?

**Comment by WanderingPhilosopher** [comment]
try now...

**Comment by sari777** [comment]
again bug. not producing public keys. only producing addresses. then how can we calculate.?

**Comment by sari777** [comment]
not producing even after removing the -f command.

**Comment by sari777** [comment]
issue resolved after typing -f publickey. but in the batch file you said you should remove it for the display of public keys.

**Comment by sari777** [comment]
interesting. now. if I don't provide the command "-x" it is not producing anything. and if I provide the command "-x" it produces keys but without + and - values. which I think are useless without + and - values. please fix this issue.

**Comment by WanderingPhilosopher** [comment]
Please try version 2; bug has been fixed. Keep the libgmp-10.dll in same folder as the .exe
